name: MergeMasterIntoQa

on:
  workflow_dispatch:
  schedule:
    # You can setup schedule here
    - cron: '0 0 * * *' #0 13 * * 1

env:
  # replace "github_username" with your GitHub username
  # replace "github.com/username/repo.git" with your GitHub repo path
  # do NOT replace ${{secrets.GITHUB_TOKEN}}, GitHub will take care of it
  MY_REPO: https://Mohit-Kumar-Anchanto:${{secrets.GITHUB_TOKEN}}@github.com/Mohit-Kumar-Anchanto/alpha-blog.git

  # replace "long-lived_branch_name" with your branch name
  MY_BRANCH: add_association

  # replace it with the path to master repo
  MASTER_REPO: https://github.com/Mohit-Kumar-Anchanto/alpha-blog.git

  # replace "master" with your master branch name
  MASTER_BRANCH: main

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Merge with main
      run: |
        git clone ${{env.MY_REPO}} -b ${{env.MY_BRANCH}} tmp
        cd tmp
        git config user.name "auto-merge"
        git config user.email "auto-merge@anchanto.com"
        git config pull.rebase false
        git pull ${{env.MASTER_REPO}} ${{env.MASTER_BRANCH}}
        git push