name: Check merged
on:
  pull_request:
    branches:
      - main

jobs:
  check-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: SonicGarden/check-merged-action@v1
        with:
          token: ${{secrets.GITHUB_TOKEN }}
          originBranch: qa-test
          title: :boom: :roll_eyes: MergeIntoQAFirst
